compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  axios@*:
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  react@*:
    dependencies:
      "@types/react": "19.0.2"
  react-dom@*:
    dependencies:
      "@types/react-dom": "19.0.2"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
