compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  axios@*:
    dependencies:
      debug: "*"
  debug@*:
    dependencies:
      supports-color: "*"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
